# This workflow will deploy the master branch to the staging server

name: deploy_staging

on:
  push:
    branches:
      - master

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: "ffb1d2cd-3e0f-4ccf-b41f-4688e8519f7c"
          heroku_app_name: "afternoon-brook-48620"
          heroku_email: "ashwin.balamohan@utoronto.ca"
