# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# It will be run on any pull request to master

name: web_ci

on:
  pull_request:
    branches: [ master ]

jobs:
  web_ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run ci
